### ISSUE TITLE
Issue on page /03.01-descriptives.html

### ISSUE THREAD

**Issue by bastiansolass** [ethanweed/pythonbook#12]
Table in section 5.2.3 is the same as the one I 5.1.1 which doesn't seem right. 
Furthermore, the code for Fig. 5.6 in section doesn't work: matplotlib.pyplot should be imported as plt, and 

dan_grump = parenthood['dan.grump']
dan_sleep = parenthood['dan.sleep']
baby_sleep = parenthood['baby.sleep']

should be:

dan_grump = parenthood['dan_grump']
dan_sleep = parenthood['dan_sleep']
baby_sleep = parenthood['baby_sleep']

**Comment by bastiansolass** [comment]
I see, however, that dan.grump, dan.sleep and baby.sleep are used throughout the rest of the chapter, so maybe the data should be changed.

**Comment by ethanweed** [comment]
I think I have fixed all of these now. Thanks Bastian :-)
