### ISSUE TITLE
Some problems with the reading fo the file in Firefox

### ISSUE THREAD

**Issue by lemelinm** [ethanweed/pythonbook#2]
First of all, I must say I am impressed by the work. Very interesting.
I am using Firefox 101.0.1 x64. In section 12.4.2 for example, after the formula of S^2, there is some problem with the codes because there is a part in bold that seems to suffer from code errors. And I have been observing that many figures referencing are not working. Of course, it is easy for me to say that, considering the amount of work that has been done, and continue to be done, I am sure. I just wanted to talk about it because I always work with Firefox.

**Comment by ethanweed** [comment]
Hi @lemelinm, thanks for the feedback! I have fixed the section you referred to, but I know there are more sections like this, and reference links that don't resolve, that I need to go back and fix. Hopefully I will get some of these rough edges smoothed out during the coming semester. If you spot more problems (and I know there are more problems lurking in there!), you are very welcome to open another issue.
