### ISSUE TITLE
https://ethanweed.github.io/pythonbook/03.01-descriptives.html#measures-of-central-tendencyIssue on page /03.01-descriptives.html

### ISSUE THREAD

**Issue by bbishop423** [ethanweed/pythonbook#28]
Corrected grammatical errors:

That is, you’d like to know something about where the “average” or “middle” of your data lies. The most commonly used measures are the mean, median and mode; occasionally people will also report a trimmed mean. I’ll explain each of these in turn, and then discuss when each of them is useful..

**Comment by ethanweed** [comment]
Fixed, thanks for pointing this out :-)
