### ISSUE TITLE
Issue on page /05.03-anova.html

### ISSUE THREAD

**Issue by lucgiffon** [ethanweed/pythonbook#33]
Screenshot of the part:

![image](https://github.com/ethanweed/pythonbook/assets/10561061/1ae2f649-ccc7-447a-8a18-faae599c10c1)

------------

I believe $\epsilon$ should be replaced with $\epsilon_{ik}$ in the last equation, for clarity.

**Comment by ethanweed** [comment]
Yeah, that seems reasonable. I will fix this - thank you!
