### ISSUE TITLE
Issue on multiple pages

### ISSUE THREAD

**Issue by alexrhogue** [ethanweed/pythonbook#7]
Big fan of this version of the book!  Here are some typos I noticed while reading through it.  

"We’ve stored these in R as the corresponding variables" in section https://ethanweed.github.io/pythonbook/05.01-chisquare.html#the-goodness-of-fit-test-statistic

"That is, what values of  x^2 would lead **is** to reject the null hypothesis" (I think it should be "would lead **us**) in section https://ethanweed.github.io/pythonbook/05.01-chisquare.html#testing-the-null-hypothesis 

Missing space between var1 and in "`var1`in" in section https://ethanweed.github.io/pythonbook/03.01-descriptives.html#the-single-variable-case

Typo "eaerlier" in section https://ethanweed.github.io/pythonbook/03.01-descriptives.html#the-single-variable-case

**Comment by ethanweed** [comment]
Thanks so much Alex, I really appreciate it!
